package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "setup_proto",
    deps = [
        ":setup_proto_lib",
    ],
)

proto_library(
    name = "setup_proto_lib",
    srcs = [
        "setup.proto",
    ],
    deps = [
    ],
)
