package(default_visibility = ["//colony:__subpackages__"])

cc_library(
    name = "factions",
    srcs = ["factions.cc"],
    hdrs = ["factions.h"],
    deps = [
        "//colony/factions/proto:factions_proto",
        "//util/arithmetic:microunits",
        "//util/headers:int_types",
    ],
)
