cc_binary(
    name = "colony",
    srcs = ["colony_main.cc"],
    deps = [
        "//games/colony/controller:controller",
        "//games/colony/interface:factory",
        "//games/colony/interface:user_interface",
    ],
)
