# Makefile for geography tests.
TARGET_NAME = geography

include libs.mk

LIBS += $(GEOGRAPHY_LIB)
LIBS += $(MARKET_LIB)
LIBS += $(PROTOBUF_LIB)
LIBS += $(INDUSTRY_LIB)
LIBS += $(STATUS_LIB)

include common.mk
include tests.mk
