package(default_visibility = ["//visibility:public"])

cc_library(
    name = "setup",
    srcs = ["setup.cc"],
    hdrs = ["setup.h"],
    deps = [
        "//games/setup/proto:setup_proto",
        "//util/proto:file",
        "//util/status",
        "@com_google_absl//absl/strings:strings",
    ],
)
