package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cost",
    srcs = ["cost.cc"],
    hdrs = ["cost.h"],
    deps = [
        "//games/actions/proto:plan_proto",
        "//games/geography:connection",
        "//games/units:units",
    ],
)
