syntax = "proto3";
package combat.proto;
option go_package = "gogames/combat/tables_proto";

import "gogames/util/logic.proto";

// Modifier is a value that applies to rolls if the predicates hold.
message Modifier {
  string key = 1;
  int32 value = 2;
  repeated util.logic.proto.Predicate requires = 3;
}

// Result is a possible outcome of a single battle phase.
message Result {
  string key = 1;
  bool ends = 2;
  string goto = 3;
  int32 pips = 4;
  repeated util.logic.proto.Predicate requires = 5;
  repeated Modifier flags = 6;
}

// Phase is a table of results.
message Phase {
  string key = 1;
  repeated int32 rolls = 2;
  repeated Modifier modifiers = 3;
  repeated Result results = 4;
}

// Outcome is the overall result of an entire resolution,
// including possibly multiple phase results.
message Outcome {
  map<string, int32> flags = 1;
  repeated Phase phases = 2;
}
