# Makefile for population tests.
TARGET_NAME = population

include libs.mk

LIBS += $(POPULATION_LIB)
LIBS += $(GEOGRAPHY_LIB)
LIBS += $(MARKET_LIB)
LIBS += $(PROTOBUF_LIB)
LIBS += $(INDUSTRY_LIB)
LIBS += $(STATUS_LIB)

include common.mk
include tests.mk
