syntax = "proto3";
package landnam.pop.proto;
option go_package = "gogames/landnam/population/pop_proto";

import "gogames/util/logic.proto";

message Demographics {
  int32 infants = 1;
  int32 children = 2;
  int32 youths = 3;
  int32 adults = 4;
  int32 elders = 5;
}

message Specialization {
  string good = 1;
  int32 level = 2;
}

message PopChange {
  string new_key = 1;
  repeated util.logic.proto.Predicate requires = 2;
}

message SpecChange {
  Specialization new_level = 1;
  repeated util.logic.proto.Predicate requires = 2;
}

message PopType {
  string key = 1;
  int32 produce = 2;
  repeated int32 consume = 3;
  repeated int32 capital = 4;
  repeated int32 militia = 5;
  repeated int32 meaning = 6;
  int32 min_consume = 7;
  int32 siz_consume = 8;
  int32 inc_consume = 9;
  Demographics births_per_thousand = 10;
  Demographics deaths_per_thousand = 11;
  int32 trade_gain_per_level = 12;
  repeated PopChange evolves = 13;
  repeated SpecChange specializations = 14;
}

message Pop {
  string key = 1;
  string kind = 2;
  Demographics people = 3;
  int32 prods = 4;
  int32 consume = 5;
  int32 capital = 6;
  int32 militia = 7;
  int32 meaning = 8;
  Specialization specialize = 9;
}
