load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "devclient",
    srcs = [
      "dev_client.go",
    ],
    importpath = "gogames/raubgraf/clients/devclient",
    deps = [
      "//gogames/raubgraf/engine:engine",
    ],
)
