package(default_visibility = ["//colony:__subpackages__"])

cc_proto_library(
    name = "factions_proto",
    deps = [":factions_proto_lib"],
)

proto_library(
    name = "factions_proto_lib",
    srcs = ["factions.proto"],
)
