package(default_visibility = ["//visibility:public"])

cc_library(
  name = "unit_ai",
  srcs = ["unit_ai.cc"],
  hdrs = ["unit_ai.h"],
  deps = [
    "//units:units",
    "//actions/proto:strategy_proto",
    "//actions/proto:plan_proto",
  ],
)
