load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "settlers",
    srcs = ["settlers.go"],
    importpath = "gogames/settlers/engine/settlers",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
