load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "client_lib",
    srcs = [
      "client_lib.go",
    ],
    importpath = "gogames/raubgraf/clients/dev/clientlib",
    deps = [
      "//gogames/raubgraf/engine:engine",
    ],
)

