package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "rankings_proto",
    deps = [
        ":rankings_proto_lib",
    ],
)

proto_library(
    name = "rankings_proto_lib",
    srcs = [
        "rankings.proto",
    ],
)
