cc_binary(
    name = "sim",
    srcs = ["sim_main.cc"],
    deps = [
        "@com_google_absl//absl/algorithm:container",
        "@com_google_absl//absl/random:random",
        "@com_google_absl//absl/flags:flag",
    ],
)
