package(default_visibility = ["//visibility:public"])

cc_library(
  name = "units",
  srcs = ["unit.cc"],
  hdrs = ["unit.h"],
  deps = [
    "//geography:mobile",
    "//units/proto:units_proto",
    "//units/proto:unit_templates_proto",
    "//util/proto:object_id",
    "@com_google_protobuf//:protobuf",
  ],
)

