cc_binary(
    name = "colony",
    srcs = ["colony_main.cc"],
    deps = [
        "//colony/controller:controller",
        "//colony/interface:factory",
        "//colony/interface:user_interface",
    ],
)
