package(default_visibility = ["//colony:__subpackages__"])

cc_library(
    name = "text_interface",
    srcs = ["text_interface.cc"],
    hdrs = ["text_interface.h"],
    deps = [
        "//colony/controller:controller",
        "//colony/interface:user_interface",
    ],
)
