package(default_visibility = ["//games/sevenyears:__subpackages__"])

cc_proto_library(
    name = "graphics_proto",
    deps = [":graphics_proto_lib"],
)

proto_library(
    name = "graphics_proto_lib",
    srcs = ["graphics.proto"],
    deps = [
    ],
)
