package(default_visibility = ["//ai:__pkg__"])

cc_library(
  name = "unit_ai_impl",
  srcs = ["unit_ai_impl.cc"],
  hdrs = ["unit_ai_impl.h"],
  deps = [
    "//ai:unit_ai",
    "//actions/proto:strategy_proto",
    "//actions/proto:plan_proto",
  ],
)
